version: "3.2"
services:
    web_app:
      restart: always
      build: ./
      command: npm start
      volumes:
        - ./src:/var/www/app/src
        - ./package.json:/var/www/app/package.json
      ports:
        - 3001:3000
        - 9229:9229