version: "3.2"
services:
    db:
      image: mysql:5.7 
      volumes:
        - db_data:/var/lib/mysql
        - ./mysql-dump:/docker-entrypoint-initdb.d
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: hh
      ports:
        - 3307:3306

    web_app:
      depends_on:
        - db
      build: ./
      volumes:
        - ./src:/var/www/app/src
        - ./package.json:/var/www/app/package.json
      command: npm start
      restart: always
      ports:
        - 3001:3000

volumes:
    db_data: {}